# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - antivirus-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Clean workspace
        run: dotnet clean --configuration Release

      - name: Delete obj and bin folders
        run: |
          if (Test-Path obj) { Remove-Item -Recurse -Force obj }
          if (Test-Path bin) { Remove-Item -Recurse -Force bin }
        shell: pwsh

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore
      
      - name: Connect to Azure VPN
        run: |
          sudo apt update && sudo apt install -y openvpn
          sudo openvpn --config vpn-config.ovpn --daemon
          echo "Esperando a que se establezca la conexión VPN..."
          sleep 20
          echo "IP pública tras VPN:"
          curl ifconfig.me


      - name: Run Entity Framework Migrations
        env:
          CONNECTION_STRING: "Server=antivirus-db.cvkm6gqukms4.us-east-2.rds.amazonaws.com;Database=antivirus;Port=5432;User Id=postgres;Password=${{ secrets.DB_PASSWORD }};Ssl Mode=Require;Trust Server Certificate=true"
        run: |
          dotnet tool install --global dotnet-ef
          dotnet ef database update --connection "$env:CONNECTION_STRING"

      - name: dotnet publish
        run: dotnet publish "./Antivirus.csproj" -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5EC3B99E5BF045528814A5FE67A304BA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_03E96F28936140C4AEC6D80DFBB58354 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1ECF6A86E70941599460FAF08F324E64 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'antivirus-backend'
          slot-name: 'Production'
          package: .
